TrackingSystem/Controllers/QuestionController.cs
using AutoMapper;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TrackingSystem.ViewModels;
using TrackingSystemBLL.Interfaces;

namespace TrackingSystem.Controllers
{
    /// <summary>
    /// Question controller
    /// </summary>
    [Authorize(Roles = "admin")]
    public class QuestionController : Controller
    {
        private readonly IMapper mapper;

        /// <summary>
        /// Construcntor.
        /// </summary>
        /// <param name="mapper">Mapper</param>
        public QuestionController(IMapper mapper)
        {
            this.mapper = mapper;
        }

        private IQuestionService QuestionService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IQuestionService>();
            }
        }

        /// <summary>
        /// https://localhost:44320/Question/Questions
        /// </summary>
        /// <param name="page">Number of page.</param>
        /// <returns></returns>
        public async Task<ActionResult> Questions(int? page)
        {
            var questions = mapper.Map<IEnumerable<FeedbackDesplay>>((await QuestionService.GetAllQuestionsDTOAsync()).OrderByDescending(q => q.Viewed));

            int pageSize = 8;
            int pageNumber = (page ?? 1);

            return View(questions.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// https://localhost:44320/Question/Details/
        /// </summary>
        /// <param name="id">Question`s id.</param>
        /// <returns></returns>
        public async Task<ActionResult> Details(int id)
        {
            var question = await QuestionService.GetQuestionDTOByIdAsync(id);

            if (question == null)
                return RedirectToAction("NotFound", "Error");
            ViewBag.Id = id;
            ViewBag.Viewed = question.Viewed;

            return View(mapper.Map<Feedback>(question));
        }

        /// <summary>
        /// https://localhost:44320/Question/Details/
        /// </summary>
        /// <param name="id">Question`s id.</param>
        /// <param name="form">Form collection.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Details(int id, FormCollection form)
        {
            var question = await QuestionService.GetQuestionDTOByIdAsync(id);

            if (question == null)
                return RedirectToAction("NotFound", "Error");

            ViewBag.Viewed = question.Viewed;

            question.Viewed = true;

            await QuestionService.UpdateAsync(question);

            return RedirectToAction("Questions");
        }

        /// <summary>
        /// https://localhost:44320/Question/Delete/
        /// </summary>
        /// <param name="id">Question`s id.</param>
        /// <param name="collection">Form collection.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {
            var question = await QuestionService.GetQuestionDTOByIdAsync(id);

            if (question == null)
                return RedirectToAction("NotFound", "Error");

            await QuestionService.DeleteAsync(id);

            return RedirectToAction("Questions");
        }
    }
}

TrackingSystem/Views/Shared/_Layout.cshtml
@{ 
    var currentAction = this.ViewContext.RouteData.GetRequiredString("action");
    var currentController = this.ViewContext.RouteData.GetRequiredString("controller");
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="pt-0 pb-0">
    <header class="p-3 mt-0 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start" id="navbarSupportedContent">
                <a href="~/Home/Index" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="~/Image/light_logo.svg" class="me-2 mt-0 mb-0" width="110" alt="Interdes Studio" />
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li>@Html.ActionLink("Services", "Index", "Home", null, new { @class = currentAction == "Index" && currentController == "Home" ? "nav-link px-2 text-secondary" : "nav-link px-2 text-white" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", null, new { @class = currentAction == "About" && currentController == "Home" ? "nav-link px-2 text-secondary" : "nav-link px-2 text-white" })</li>
                </ul>
                <div class="text-end">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Login", "Login", "Home", null, new { @class = "btn btn-outline-light me-2" })
                    }
                    @if (User.IsInRole("admin"))
                    {
                        @Html.ActionLink("Add employee", "Registretion", "Account", null, new { @class = "btn btn-warning" })
                        <span>&nbsp;</span>
                        @Html.ActionLink("Create new task", "Create", "Task", null, new { @class = "btn btn-warning" })
                        <span>&nbsp;</span>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (currentAction != "Index" || currentController != "Account")
                        {
                            <a class="btn btn-warning me-2" href="/Account/Employees">
                                <img class="bi bi-person-circle" src="~/Image/person-circle.svg" alt="Profile" />
                                Profile
                            </a>
                        }
                        @Html.ActionLink("Sign out", "Logout", "Home", null, new { @class = "btn btn-outline-light me-2" })
                    }
                </div>
            </div>
        </div>
    </header>

    <div class="container mb-4">
        @RenderBody()
    </div>

    @RenderSection("form", false)

    <div class="container mt-lg-5">
        <footer>
            <div class="row">
                <div class="col-md-2">
                    <a href="~/Home/Index" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                        <img src="~/Image/logo_bez_koronadasha.svg" class="me-2 mt-0 mb-0" width="110" alt="Interdes Studio" />
                    </a>
                </div>
                <div class="col-md-3"></div>
                <div class="col-md-2">
                    <br />
                    <h5 class="me-2">Follow</h5>
                </div>
                <div class="col-md-3"></div>
                <div class="col-md-2">
                    <br />
                    <h5 class="me-2">Contact</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <hr />
                </div>
                <div class="col-md-3"></div>
                <div class="col-md-2">
                    <hr />
                </div>
                <div class="col-md-3"></div>
                <div class="col-md-2">
                    <hr />
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.ActionLink("services", "Index", "Home", null, new { @class = "text-decoration-none text-dark" })
                    <br />
                    @Html.ActionLink("about", "About", "Home", null, new { @class = "text-decoration-none text-dark" })
                </div>
                <div class="col-md-3"></div>
                <div class="col-md-2">
                    Instagram<br />
                    Twitter<br />
                    YouTube
                </div>
                <div class="col-md-3"></div>
                <div class="col-md-2">
                    *phone*<br />
                    *mail*
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-6 pt-xxl-5">
                    <small class="align-bottom">&copy; 2021-@DateTime.Now.Year - All rights reserved.</small>
                </div>
                <div class="col-md-6">
                    <img class="float-end me-2 mt-0 mb-0" src="~/Image/flowers.svg" width="65" />
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TrackingSystem/Views/Shared/_LayoutError.cshtml
@{ 
    var currentAction = this.ViewContext.RouteData.GetRequiredString("action");
    var currentController = this.ViewContext.RouteData.GetRequiredString("controller");
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="pt-0 bg-secondary"> 
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TrackingSystem/Views/Shared/_LayoutProfile.cshtml
@{
    var currentAction = this.ViewContext.RouteData.GetRequiredString("action");
    var currentController = this.ViewContext.RouteData.GetRequiredString("controller");
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
</head>
<body class="pt-0">
    <header class="p-3 mt-0 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start" id="navbarSupportedContent">
                <a href="~/Home/Index" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="~/Image/light_logo.svg" class="me-2 mt-0 mb-0" width="110" alt="Interdes Studio" />
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li>@Html.ActionLink("Services", "Index", "Home", null, new { @class = currentAction == "Index" && currentController == "Home" ? "nav-link px-2 text-secondary" : "nav-link px-2 text-white" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", null, new { @class = currentAction == "About" && currentController == "Home" ? "nav-link px-2 text-secondary" : "nav-link px-2 text-white" })</li>
                </ul>
                <div class="text-end">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Login", "Login", "Home", null, new { @class = "btn btn-outline-light me-2" })
                    }
                    @if (User.IsInRole("admin"))
                    {
                        @Html.ActionLink("Add employee", "Registretion", "Account", null, new { @class = "btn btn-warning" })
                        <span>&nbsp;</span>
                        @Html.ActionLink("Create new task", "Create", "Task", null, new { @class = "btn btn-warning" })
                    }
                </div>
            </div>
        </div>
    </header>

    <div class="col-md-11">
        <div class="row">
            <div class="col-md-2">
                <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: auto; height: 91vh">
                    <span class="fs-4">@User.Identity.Name.Substring(0, User.Identity.Name.IndexOf('@'))</span>
                    <hr>
                    <ul class="nav nav-pills flex-column mb-auto">
                        <li class="nav-item">
                            @Html.ActionLink("Employees", "Employees", "Account", null, new { @class = currentController == "Account" ? "nav-link text-dark bg-warning" : "nav-link link-dark" })
                        </li>
                        <li>
                            @Html.ActionLink("Tasks", "Tasks", "Task", null, new { @class = currentController == "Task" ? "nav-link text-dark bg-warning" : "nav-link link-dark" })
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                        <li>
                            @Html.ActionLink("Customer questions", "Questions", "Question", null, new { @class = currentController == "Question" ? "nav-link text-dark bg-warning" : "nav-link link-dark" })
                        </li>
                        }
                    </ul>
                    <hr>
                    <a href="/Home/Logout" class="nav-link link-dark fs-5">Sign out</a>
                </div>
            </div>
            <div class="col-md-10">
                <div class="container">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>